#!/bin/bash
#
# Links the contents of the `dotfiles` directory into the home directory,
# prefixing each with a `.`.
# Author: Noah Silas
# Source: github.com/noahsilas/dotfiles/

RELATIVE_PATH=`dirname $0`
DOTFILES_PATH=`( cd ${RELATIVE_PATH}/dotfiles && pwd )`

for FILE in $DOTFILES_PATH/*; do
    DEST=~/.`basename $FILE`

    if [[ -L $DEST ]] && [[ `readlink $DEST` == $FILE ]]; then
        # The link is already to the destination; we don't need to do
        # anything.
        continue
    fi

    ln -s $FILE $DEST
done

# For windows CMD, instruct how to map 'g' to 'git'
# https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script
unamestr=`uname`
if [[ $unamestr == MINGW64* ]]; then
  echo " "
  echo "WINDOWS SYSTEM DETECTED"
  echo "  In order to map 'g' to 'git', Open 'regedit' go to "
  echo "  HKEY_CURRENT_USER\\Software\\Microsoft\\Command Processor"
  echo "  Add String Value entry with the name 'AutoRun' and the path:"
  echo "  $USERPROFILE\\.win-alias.cmd"
fi
